version: '3.8'

services:
  database:
    container_name: gps-database
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: tracker
      MYSQL_USER: tracker
      MYSQL_PASSWORD: tracker123
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: gps-php
    build:
      context: ./docker
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
  nginx:
    container_name: gps-nginx
    image: nginx:stable-alpine
    ports:
      - '8085:80'
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
