name: "Lint and Analyze"

on:
    pull_request:
    push:
        branches:
            - main

env:
    fail-fast: true

jobs:
    lint:
        name: "Lint and Analyze / PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['8.2']

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: "intl, mbstring, pdo_sqlite"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: "Cache composer"
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - name: "Install dependencies"
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: "Install PHP_CodeSniffer"
              run: composer global require "squizlabs/php_codesniffer=*"

            - name: "Run PHP_CodeSniffer"
              run: ~/.composer/vendor/bin/phpcs --standard=PSR12 src/

            - name: "Run PHP_CodeSniffer and Auto-fix"
              run: ~/.composer/vendor/bin/phpcbf --standard=PSR12 src/

            - name: "Run PHPStan"
              run: ./vendor/bin/phpstan analyze

            - name: "Run PHPUnit"
              run: ./vendor/bin/phpunit

            - name: "Install PHP CS Fixer"
              run: composer require --dev friendsofphp/php-cs-fixer

            - name: "Run PHP CS Fixer"
              run: vendor/bin/php-cs-fixer fix --diff --dry-run src/
